#!/usr/bin/env bash

sass --watch csswizardry.scss:../_includes/css/csswizardry.min.css \
     --style=compressed \
     --no-source-map \
     --load-path bower_components \
     --quiet-deps \
     --silence-deprecation=import

exit 0
